version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=tzs_stablecoin
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - XRPL_NETWORK=testnet
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tzs_stablecoin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
