[build]
  publish = "frontend/dashboard/out"
  command = "cd frontend/dashboard && npm run build"
  functions = "frontend/dashboard/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  DATABASE_URL = "postgresql://neondb_owner:npg_3EJCNTnzM9PF@ep-green-poetry-a26ov6e8-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "cd frontend/dashboard && npm run build"

[context.deploy-preview]
  command = "cd frontend/dashboard && npm run build"

[context.branch-deploy]
  command = "cd frontend/dashboard && npm run build"
